spring:
  profiles:
    active: prod
---

spring:
  console:
    enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

  thymeleaf:
    check-template-location: true
    cache: false

  mvc:
    static-path-pattern: "/static/**"
  config:
    activate:
      on-profile: dev

logging.level:
  org.hibernate.SQL: debug

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthner?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: healthner
    password: admin123
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
     hibernate:
       format_sql: true

  thymeleaf:
    check-template-location: true
    cache: false

  mvc:
    static-path-pattern: "/static/**"
  config:
    activate:
      on-profile: prod

logging.level:
  org.hibernate.SQL: debug